<!DOCTYPE html>
<html>
<head>
<title>View Retinue | {$retinue->name|escape} | {$SITE_NAME|escape}</title>
<link rel="stylesheet" type="text/css" href="/css/style.css" />
<link href='https://fonts.googleapis.com/css?family=IM+Fell+DW+Pica' rel='stylesheet' type='text/css'><style type="text/css">{literal}

p, div, span, table, tr, td, th, ul, ol, li, form, input, select, option, textarea, button {
	font-family: Times, "Times New Roman", serif;
}

h1,h2,h3,h4,h5,h6,th {
font-family: "IM Fell DW Pica" !important;
}

p,span,div,table,tr,td,th,ul,ol,li {
font-size:10pt;
}
{/literal}</style>
</head>
<body>
<h1 style="text-align:center">In The Emperor's Name</h1>

{if $error}
	<p style="text-align:center">Error: {$error}</p>

{else}
	<h2 style="text-align:center">{$retinue->name|escape}</h2>

	{assign var=race value=$retinue->getRace()}
	<h3 style="text-align:center">Faction: {$race->name}</h3>

	{assign var=creator value=$retinue->getCreator()}
	<p style="text-align:center">Created by {$creator->username|escape|capitalize}</p>

	{include file="figure-list.tpl" figures=$retinue->getFigures() read_only=true printable=true}

	<p class="ret-notes">Notes: <em>{$retinue->notes|escape|nl2br}</em></p>

	<p style="text-align:center"><em>
		This Retinue List was generated by the {$SITE_NAME|escape}<br/>
		Permanent Link: https://{$smarty.server.HTTP_HOST}/view_retinue?id={$retinue->id|escape}
	</em></p>
{/if}

</body></html>
